api:
  base_url: http://127.0.0.1:8000
inference_defaults:
  app_key: ''
  batch_size: 1
  batch_threshold: 0.75
  dl_url: ''
  fragment_interval: 0.3
  if_sr: false
  media_type: wav
  parallel_infer: true
  prompt_text_lang: 中文
  repetition_penalty: 1.35
  sample_steps: 16
  seed: -1
  speed_facter: 1.0
  split_bucket: true
  temperature: 1.0
  text_lang: 中文
  text_split_method: 按标点符号切
  top_k: 10
  top_p: 1.0
  version: v4
